NEWS_SOURCES = [
    {
        "name": "Hiiraan Online",
        "url": "https://www.hiiraan.com/rss.xml",
        "homepage": "https://www.hiiraan.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "SONNA English",
        "url": "https://sonna.so/en/feed/",
        "homepage": "https://sonna.so/en/",
        "region": "somalia",
        "section": "Somalia",
        "category": "State agency",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Shabelle Media",
        "url": "https://shabellemedia.com/feed/",
        "homepage": "https://shabellemedia.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Goobjoog English",
        "url": "https://en.goobjoog.com/feed/",
        "homepage": "https://en.goobjoog.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Caasimada Online",
        "url": "https://www.caasimada.net/feed/",
        "homepage": "https://www.caasimada.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "Jowhar",
        "url": "https://jowhar.com/feed/",
        "homepage": "https://jowhar.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Puntland Post",
        "url": "https://puntlandpost.net/feed/",
        "homepage": "https://puntlandpost.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Horseed Media",
        "url": "https://horseedmedia.net/feed/",
        "homepage": "https://horseedmedia.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Somali Guardian",
        "url": "https://www.somaliguardian.com/feed/",
        "homepage": "https://www.somaliguardian.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "Somali Dispatch",
        "url": "https://www.somalidispatch.com/feed/",
        "homepage": "https://www.somalidispatch.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "The Somali Digest",
        "url": "https://thesomalidigest.com/feed/",
        "homepage": "https://thesomalidigest.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Analysis and politics",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "Wardheer News",
        "url": "https://wardheernews.com/feed/",
        "homepage": "https://wardheernews.com/",
        "region": "diaspora",
        "section": "Somalia",
        "category": "Diaspora and opinion",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "AllAfrica Somalia",
        "url": "https://allafrica.com/tools/headlines/rdf/somalia/headlines.rdf",
        "homepage": "https://allafrica.com/somalia/",
        "region": "africa",
        "section": "Africa",
        "category": "Africa aggregator",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "ReliefWeb Somalia",
        "url": "https://reliefweb.int/updates/rss.xml?advanced-search=%28PC255%29",
        "homepage": "https://reliefweb.int/country/som",
        "region": "humanitarian",
        "section": "Humanitarian",
        "category": "Humanitarian",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "The Guardian Somalia",
        "url": "https://www.theguardian.com/world/somalia/rss",
        "homepage": "https://www.theguardian.com/world/somalia",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "New York Times Somalia",
        "url": "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/somalia/rss.xml",
        "homepage": "https://www.nytimes.com/topic/destination/somalia",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "BBC World",
        "url": "http://feeds.bbci.co.uk/news/world/rss.xml",
        "homepage": "https://www.bbc.com/news/world",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "homepage": "https://www.aljazeera.com/",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 3,
    },
]


SOURCE_BY_NAME = {source["name"]: source for source in NEWS_SOURCES}
