NEWS_SOURCES = [
    {
        "name": "Hiiraan Online",
        "url": "https://www.hiiraan.com/rss.xml",
        "homepage": "https://www.hiiraan.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "SONNA English",
        "url": "https://sonna.so/en/feed/",
        "homepage": "https://sonna.so/en/",
        "region": "somalia",
        "section": "Somalia",
        "category": "State agency",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Radio Muqdisho",
        "url": "https://radiomuqdisho.so/feed/",
        "homepage": "https://radiomuqdisho.so/",
        "region": "somalia",
        "section": "Somalia",
        "category": "State broadcaster",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "Somali National TV",
        "url": "https://sntv.so/feed/",
        "homepage": "https://sntv.so/",
        "region": "somalia",
        "section": "Somalia",
        "category": "State broadcaster",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "BBC Somali",
        "url": "https://feeds.bbci.co.uk/somali/rss.xml",
        "homepage": "https://www.bbc.com/somali",
        "region": "international",
        "section": "Somalia",
        "category": "Somali-language international",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "VOA Somali",
        "url": "https://www.voasomali.com/api/zoju_l-vomx-tpep_jy",
        "homepage": "https://www.voasomali.com/",
        "region": "international",
        "section": "Somalia",
        "category": "Somali-language international",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "Shabelle Media",
        "url": "https://shabellemedia.com/feed/",
        "homepage": "https://shabellemedia.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Goobjoog English",
        "url": "https://en.goobjoog.com/feed/",
        "homepage": "https://en.goobjoog.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 1,
    },
    {
        "name": "Caasimada Online",
        "url": "https://www.caasimada.net/feed/",
        "homepage": "https://www.caasimada.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "Raxanreeb Online",
        "url": "https://raxanreeb.com/feed/",
        "homepage": "https://raxanreeb.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "so",
        "priority": 1,
    },
    {
        "name": "Jowhar",
        "url": "https://jowhar.com/feed/",
        "homepage": "https://jowhar.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Puntland Post",
        "url": "https://puntlandpost.net/feed/",
        "homepage": "https://puntlandpost.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Horseed Media",
        "url": "https://horseedmedia.net/feed/",
        "homepage": "https://horseedmedia.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Hiiraanweyn",
        "url": "https://www.hiiraanweyn.net/feed/",
        "homepage": "https://www.hiiraanweyn.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Puntland Mirror",
        "url": "https://puntlandmirror.net/feed/",
        "homepage": "https://puntlandmirror.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "Somali Guardian",
        "url": "https://www.somaliguardian.com/feed/",
        "homepage": "https://www.somaliguardian.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "Somali Dispatch",
        "url": "https://www.somalidispatch.com/feed/",
        "homepage": "https://www.somalidispatch.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "The Somali Digest",
        "url": "https://thesomalidigest.com/feed/",
        "homepage": "https://thesomalidigest.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Analysis and politics",
        "language": "en",
        "priority": 2,
    },
    {
        "name": "Idil News",
        "url": "https://www.idilnews.com/feed/",
        "homepage": "https://www.idilnews.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Mudug24",
        "url": "https://mudug24.com/feed/",
        "homepage": "https://mudug24.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 2,
    },
    {
        "name": "Goobjooge",
        "url": "https://goobjooge.net/feed/",
        "homepage": "https://goobjooge.net/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Somali national",
        "language": "so",
        "priority": 3,
    },
    {
        "name": "AllSanaag",
        "url": "https://allsanaag.com/feed/",
        "homepage": "https://allsanaag.com/",
        "region": "somalia",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 3,
    },
    {
        "name": "Wardheer News",
        "url": "https://wardheernews.com/feed/",
        "homepage": "https://wardheernews.com/",
        "region": "diaspora",
        "section": "Somalia",
        "category": "Diaspora and opinion",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "Radio Ergo",
        "url": "https://radioergo.org/en/feed/",
        "homepage": "https://radioergo.org/",
        "region": "humanitarian",
        "section": "Humanitarian",
        "category": "Humanitarian",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "Somaliland Chronicle",
        "url": "https://somalilandchronicle.com/feed/",
        "homepage": "https://somalilandchronicle.com/",
        "region": "somaliland",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "Berbera News",
        "url": "https://berberanews.net/feed/",
        "homepage": "https://berberanews.net/",
        "region": "somaliland",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 3,
    },
    {
        "name": "Wargeyska Dawan",
        "url": "https://wargeyskadawan.com/feed/",
        "homepage": "https://wargeyskadawan.com/",
        "region": "somaliland",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 3,
    },
    {
        "name": "Oodweyne Media",
        "url": "https://www.oodweynemedia.com/feed/",
        "homepage": "https://www.oodweynemedia.com/",
        "region": "somaliland",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "so",
        "priority": 3,
    },
    {
        "name": "Saxafi Media",
        "url": "https://saxafimedia.com/feed/",
        "homepage": "https://saxafimedia.com/",
        "region": "somaliland",
        "section": "Somalia",
        "category": "Regional Somali",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "AllAfrica Somalia",
        "url": "https://allafrica.com/tools/headlines/rdf/somalia/headlines.rdf",
        "homepage": "https://allafrica.com/somalia/",
        "region": "africa",
        "section": "Africa",
        "category": "Africa aggregator",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "ReliefWeb Somalia",
        "url": "https://reliefweb.int/updates/rss.xml?advanced-search=%28PC255%29",
        "homepage": "https://reliefweb.int/country/som",
        "region": "humanitarian",
        "section": "Humanitarian",
        "category": "Humanitarian",
        "language": "en",
        "priority": 3,
    },
    {
        "name": "The Guardian Somalia",
        "url": "https://www.theguardian.com/world/somalia/rss",
        "homepage": "https://www.theguardian.com/world/somalia",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 4,
    },
    {
        "name": "New York Times Somalia",
        "url": "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/topic/destination/somalia/rss.xml",
        "homepage": "https://www.nytimes.com/topic/destination/somalia",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 4,
    },
    {
        "name": "BBC World",
        "url": "http://feeds.bbci.co.uk/news/world/rss.xml",
        "homepage": "https://www.bbc.com/news/world",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 4,
    },
    {
        "name": "New York Times Africa",
        "url": "https://rss.nytimes.com/services/xml/rss/nyt/Africa.xml",
        "homepage": "https://www.nytimes.com/section/world/africa",
        "region": "africa",
        "section": "Africa",
        "category": "Africa context",
        "language": "en",
        "priority": 4,
    },
    {
        "name": "BBC Africa",
        "url": "https://feeds.bbci.co.uk/news/world/africa/rss.xml",
        "homepage": "https://www.bbc.com/news/world/africa",
        "region": "africa",
        "section": "Africa",
        "category": "Africa context",
        "language": "en",
        "priority": 4,
    },
    {
        "name": "Al Jazeera",
        "url": "https://www.aljazeera.com/xml/rss/all.xml",
        "homepage": "https://www.aljazeera.com/",
        "region": "international",
        "section": "World",
        "category": "International publisher",
        "language": "en",
        "priority": 4,
    },
]


SOURCE_BY_NAME = {source["name"]: source for source in NEWS_SOURCES}
