from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Optional


@dataclass(frozen=True)
class SourceCandidate:
    id: str
    name: str
    source_type: str
    base_url: str
    feed_url: str
    language: str
    category: str
    priority: int
    is_enabled: bool = False
    validation_status: str = "pending"
    last_validated_at: Optional[str] = None
    last_error: Optional[str] = None
    consecutive_failures: int = 0
    notes: str = ""
    country: str = "SO"
    description: str = ""

    def to_seed_payload(self) -> dict[str, object]:
        payload = asdict(self)
        payload["is_active"] = payload.pop("is_enabled")
        payload["last_error_message"] = payload.pop("last_error")
        payload.pop("last_validated_at")
        payload.pop("consecutive_failures")
        return payload


SOURCE_CANDIDATES = [
    SourceCandidate(
        id="bbc-somali",
        name="BBC Somali",
        source_type="rss",
        base_url="https://www.bbc.com/somali",
        feed_url="https://feeds.bbci.co.uk/somali/rss.xml",
        language="so",
        category="international_context",
        priority=10,
        description="Somali-language coverage from BBC Somali.",
        country="GB",
        notes="High-signal Somali-language international source.",
    ),
    SourceCandidate(
        id="voa-somali",
        name="VOA Somali",
        source_type="rss",
        base_url="https://www.voasomali.com",
        feed_url="https://www.voasomali.com/api/zoju_l-vomx-tpep_jy",
        language="so",
        category="international_context",
        priority=15,
        description="Somali-language news and interviews from VOA Somali.",
        country="US",
        notes="Official VOA Somali RSS/API feed.",
    ),
    SourceCandidate(
        id="sonna",
        name="SONNA English",
        source_type="rss",
        base_url="https://sonna.so/en",
        feed_url="https://sonna.so/en/feed/",
        language="en",
        category="official",
        priority=20,
        description="Official Somali National News Agency English feed.",
        notes="Government-aligned national source.",
    ),
    SourceCandidate(
        id="radio-muqdisho",
        name="Radio Muqdisho",
        source_type="rss",
        base_url="https://radiomuqdisho.so",
        feed_url="https://radiomuqdisho.so/feed/",
        language="so",
        category="official",
        priority=25,
        description="Public service Somali-language news from Radio Muqdisho.",
        notes="Strong official reporting, often includes images.",
    ),
    SourceCandidate(
        id="sntv",
        name="Somali National TV",
        source_type="rss",
        base_url="https://sntv.so",
        feed_url="https://sntv.so/feed/",
        language="so",
        category="official",
        priority=30,
        description="Somali National TV public news feed.",
        notes="Official broadcaster coverage.",
    ),
    SourceCandidate(
        id="hiiraan-online",
        name="Hiiraan Online",
        source_type="rss",
        base_url="https://www.hiiraan.com",
        feed_url="https://www.hiiraan.com/news.xml",
        language="en",
        category="somali_national",
        priority=35,
        description="Somali national news and diaspora-focused coverage from Hiiraan Online.",
        notes="Use news.xml; rss.xml currently returns no entries.",
    ),
    SourceCandidate(
        id="shabelle-media",
        name="Shabelle Media",
        source_type="rss",
        base_url="https://shabellemedia.com",
        feed_url="https://shabellemedia.com/feed/",
        language="en",
        category="somali_national",
        priority=40,
        description="Somali national and regional reporting from Shabelle Media.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="goobjoog-en",
        name="Goobjoog English",
        source_type="rss",
        base_url="https://en.goobjoog.com",
        feed_url="https://en.goobjoog.com/feed/",
        language="en",
        category="somali_national",
        priority=45,
        description="English-language Somali current affairs and national reporting.",
        notes="English edition feed.",
    ),
    SourceCandidate(
        id="goobjoog",
        name="Goobjoog Somali",
        source_type="rss",
        base_url="https://goobjoog.com",
        feed_url="https://goobjoog.com/feed/",
        language="so",
        category="somali_national",
        priority=50,
        description="Somali-language current affairs and national reporting from Goobjoog.",
        notes="Somali edition feed.",
    ),
    SourceCandidate(
        id="caasimada",
        name="Caasimada Online",
        source_type="rss",
        base_url="https://www.caasimada.net",
        feed_url="https://www.caasimada.net/feed/",
        language="so",
        category="somali_national",
        priority=55,
        description="Somali political and general news from Caasimada.",
        notes="Good national politics coverage.",
    ),
    SourceCandidate(
        id="raxanreeb",
        name="Raxanreeb Online",
        source_type="rss",
        base_url="https://raxanreeb.com",
        feed_url="https://raxanreeb.com/feed/",
        language="so",
        category="somali_national",
        priority=60,
        description="Somali-language political and national news.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="radio-dalsan",
        name="Radio Dalsan",
        source_type="rss",
        base_url="https://radiodalsan.com",
        feed_url="https://radiodalsan.com/feed/",
        language="so",
        category="somali_national",
        priority=65,
        description="Somali radio and web reporting from Radio Dalsan.",
        notes="Verified feed in latest check.",
    ),
    SourceCandidate(
        id="jowhar",
        name="Jowhar",
        source_type="rss",
        base_url="https://jowhar.com",
        feed_url="https://jowhar.com/feed/",
        language="so",
        category="somali_regional",
        priority=70,
        description="Somali-language regional and national reporting.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="puntland-post",
        name="Puntland Post",
        source_type="rss",
        base_url="https://puntlandpost.net",
        feed_url="https://puntlandpost.net/feed/",
        language="so",
        category="puntland",
        priority=75,
        description="Regional reporting focused on Puntland and Somali politics.",
        notes="Publishes Somali and English coverage.",
    ),
    SourceCandidate(
        id="horseed-media",
        name="Horseed Media",
        source_type="rss",
        base_url="https://horseedmedia.net",
        feed_url="https://horseedmedia.net/feed/",
        language="so",
        category="puntland",
        priority=80,
        description="Somali news and analysis with strong Puntland coverage.",
        notes="Currently a stable feed.",
    ),
    SourceCandidate(
        id="hiiraanweyn",
        name="Hiiraanweyn",
        source_type="rss",
        base_url="https://www.hiiraanweyn.net",
        feed_url="https://www.hiiraanweyn.net/feed/",
        language="so",
        category="somali_regional",
        priority=85,
        description="Somali-language regional and national news.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="puntland-mirror",
        name="Puntland Mirror",
        source_type="rss",
        base_url="https://puntlandmirror.net",
        feed_url="https://puntlandmirror.net/feed/",
        language="en",
        category="puntland",
        priority=90,
        description="English-language Puntland and Somali political reporting.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="somali-guardian",
        name="Somali Guardian",
        source_type="rss",
        base_url="https://www.somaliguardian.com",
        feed_url="https://www.somaliguardian.com/feed/",
        language="en",
        category="somali_national",
        priority=95,
        description="Somali Guardian politics and breaking developments.",
        notes="Verified feed.",
    ),
    SourceCandidate(
        id="somali-dispatch",
        name="Somali Dispatch",
        source_type="rss",
        base_url="https://www.somalidispatch.com",
        feed_url="https://www.somalidispatch.com/feed/",
        language="en",
        category="diaspora",
        priority=100,
        description="English-language Somali politics, society, and diaspora coverage.",
        notes="Useful for Somali people and diaspora angles.",
    ),
    SourceCandidate(
        id="somali-digest",
        name="The Somali Digest",
        source_type="rss",
        base_url="https://thesomalidigest.com",
        feed_url="https://thesomalidigest.com/feed/",
        language="en",
        category="analysis",
        priority=105,
        description="English-language Somalia analysis and features.",
        notes="Analysis source; watch duplicate/opinion mix.",
    ),
    SourceCandidate(
        id="wardheer-news",
        name="Wardheer News",
        source_type="rss",
        base_url="https://wardheernews.com",
        feed_url="https://wardheernews.com/feed/",
        language="en",
        category="diaspora",
        priority=110,
        description="Somali diaspora, opinion, and Horn of Africa commentary.",
        notes="Useful for diaspora views; classify as analysis/opinion where relevant.",
    ),
    SourceCandidate(
        id="radio-ergo",
        name="Radio Ergo",
        source_type="rss",
        base_url="https://radioergo.org",
        feed_url="https://radioergo.org/en/feed/",
        language="en",
        category="humanitarian",
        priority=115,
        description="Humanitarian reporting from and about Somali communities.",
        notes="Strong rural, drought, displacement, and livelihood coverage.",
    ),
    SourceCandidate(
        id="somaliland-chronicle",
        name="Somaliland Chronicle",
        source_type="rss",
        base_url="https://somalilandchronicle.com",
        feed_url="https://somalilandchronicle.com/feed/",
        language="en",
        category="somaliland",
        priority=120,
        description="English-language Somaliland politics and governance coverage.",
        notes="Regional Somaliland source.",
    ),
    SourceCandidate(
        id="berbera-news",
        name="Berbera News",
        source_type="rss",
        base_url="https://berberanews.net",
        feed_url="https://berberanews.net/feed/",
        language="so",
        category="somaliland",
        priority=125,
        description="Somali-language Somaliland and regional coverage.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="wargeyska-dawan",
        name="Wargeyska Dawan",
        source_type="rss",
        base_url="https://wargeyskadawan.com",
        feed_url="https://wargeyskadawan.com/feed/",
        language="so",
        category="somaliland",
        priority=130,
        description="Somali-language Somaliland public newspaper coverage.",
        notes="Government-aligned Somaliland source.",
    ),
    SourceCandidate(
        id="oodweyne-media",
        name="Oodweyne Media",
        source_type="rss",
        base_url="https://www.oodweynemedia.com",
        feed_url="https://www.oodweynemedia.com/feed/",
        language="so",
        category="somaliland",
        priority=135,
        description="Somali-language Somaliland and diaspora news coverage.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="saxafi-media",
        name="Saxafi Media",
        source_type="rss",
        base_url="https://saxafimedia.com",
        feed_url="https://saxafimedia.com/feed/",
        language="en",
        category="somaliland",
        priority=140,
        description="English-language Somaliland and Horn of Africa reporting.",
        notes="Verified WordPress feed.",
    ),
    SourceCandidate(
        id="allafrica-somalia",
        name="AllAfrica Somalia",
        source_type="rss",
        base_url="https://allafrica.com/somalia/",
        feed_url="https://allafrica.com/tools/headlines/rdf/somalia/headlines.rdf",
        language="en",
        category="africa_context",
        priority=145,
        description="Africa-wide aggregator feed filtered to Somalia.",
        country="ZA",
        notes="Aggregator; duplicate detection is important.",
    ),
    SourceCandidate(
        id="reliefweb-somalia",
        name="ReliefWeb Somalia",
        source_type="rss",
        base_url="https://reliefweb.int/country/som",
        feed_url="https://reliefweb.int/updates/rss.xml?advanced-search=%28PC255%29",
        language="en",
        category="humanitarian",
        priority=150,
        description="Humanitarian updates and reports filtered to Somalia.",
        country="UN",
        notes="High-signal humanitarian context; includes reports as well as news.",
    ),
    SourceCandidate(
        id="guardian-somalia",
        name="The Guardian Somalia",
        source_type="rss",
        base_url="https://www.theguardian.com/world/somalia",
        feed_url="https://www.theguardian.com/world/somalia/rss",
        language="en",
        category="international_context",
        priority=155,
        description="Guardian world coverage filtered to Somalia.",
        country="GB",
        notes="International context source.",
    ),
    SourceCandidate(
        id="garowe-online",
        name="Garowe Online",
        source_type="rss",
        base_url="https://www.garoweonline.com",
        feed_url="https://www.garoweonline.com/en/rss-feed",
        language="en",
        category="puntland",
        priority=900,
        description="Garowe-based regional Somali reporting.",
        notes="Kept as candidate; latest check returned HTTP 500 for RSS.",
    ),
]


def registry_seed_payloads() -> list[dict[str, object]]:
    return [candidate.to_seed_payload() for candidate in SOURCE_CANDIDATES]


def registry_source_ids() -> set[str]:
    return {candidate.id for candidate in SOURCE_CANDIDATES}
